// services/panss.ts

export interface PANSSAssessmentRow {
  name: string
  patient: string
  patient_name: string
  assessment_date: string
  rater: string
  positive_total: number
  negative_total: number
  general_total: number
  panss_total: number
  composite_index: number
  severity_band: string
  docstatus: number
  clinical_notes?: string
}

export interface PANSSRatings {
  // Positive Scale
  p1: number; p2: number; p3: number; p4: number; p5: number; p6: number; p7: number;
  // Negative Scale
  n1: number; n2: number; n3: number; n4: number; n5: number; n6: number; n7: number;
  // General Scale
  g1: number; g2: number; g3: number; g4: number; g5: number; g6: number;
  g7: number; g8: number; g9: number; g10: number; g11: number; g12: number;
  g13: number; g14: number; g15: number; g16: number;
}

export interface PANSSQuestion {
  code: string
  name: string
  category: 'Positive' | 'Negative' | 'General'
}

export const RATING_OPTIONS = [
  { score: 1, label: "1 - Absent" },
  { score: 2, label: "2 - Minimal" },
  { score: 3, label: "3 - Mild" },
  { score: 4, label: "4 - Moderate" },
  { score: 5, label: "5 - Moderate Severe" },
  { score: 6, label: "6 - Severe" },
  { score: 7, label: "7 - Extreme" },
]

// Question definitions with descriptions
export const POSITIVE_QUESTIONS = [
  { code: "p1", name: "Delusions", description: "Beliefs which are unfounded, unrealistic and idiosyncratic.", category: "Positive" as const },
  { code: "p2", name: "Conceptual Disorganisation", description: "Disorganised process of thinking characterised by disruption of goal-directed sequencing.", category: "Positive" as const },
  { code: "p3", name: "Hallucinatory Behaviour", description: "Verbal report or behaviour indicating perceptions not generated by external stimuli.", category: "Positive" as const },
  { code: "p4", name: "Excitement", description: "Hyperactivity as reflected in accelerated motor behaviour, heightened responsivity to stimuli.", category: "Positive" as const },
  { code: "p5", name: "Grandiosity", description: "Exaggerated self-opinion and unrealistic convictions of superiority.", category: "Positive" as const },
  { code: "p6", name: "Suspiciousness / Persecution", description: "Unrealistic or exaggerated ideas of persecution.", category: "Positive" as const },
  { code: "p7", name: "Hostility", description: "Verbal and nonverbal expressions of anger and resentment.", category: "Positive" as const },
]

export const NEGATIVE_QUESTIONS = [
  { code: "n1", name: "Blunted Affect", description: "Diminished emotional responsiveness as characterised by a reduction in facial expression.", category: "Negative" as const },
  { code: "n2", name: "Emotional Withdrawal", description: "Lack of interest in, involvement with, and affective commitment to life's events.", category: "Negative" as const },
  { code: "n3", name: "Poor Rapport", description: "Lack of interpersonal empathy, openness in conversation and sense of closeness.", category: "Negative" as const },
  { code: "n4", name: "Passive / Apathetic Social Withdrawal", description: "Diminished interest and initiative in social interactions due to passivity, apathy or avolition.", category: "Negative" as const },
  { code: "n5", name: "Difficulty in Abstract Thinking", description: "Impairment in the use of the abstract-symbolic mode of thinking.", category: "Negative" as const },
  { code: "n6", name: "Lack of Spontaneity & Flow of Conversation", description: "Reduction in the normal flow of communication associated with apathy, avolition or cognitive deficit.", category: "Negative" as const },
  { code: "n7", name: "Stereotyped Thinking", description: "Decreased fluidity, spontaneity and flexibility of thinking, as evidenced in rigid or repetitious thought content.", category: "Negative" as const },
]

export const GENERAL_QUESTIONS = [
  { code: "g1", name: "Somatic Concern", description: "Physical complaints or beliefs about bodily illness or malfunctions.", category: "General" as const },
  { code: "g2", name: "Anxiety", description: "Subjective experience of nervousness, worry, apprehension or restlessness.", category: "General" as const },
  { code: "g3", name: "Guilt Feelings", description: "Sense of remorse or self-blame for real or imagined misdeeds in the past.", category: "General" as const },
  { code: "g4", name: "Tension", description: "Overt physical manifestations of fear, anxiety and agitation.", category: "General" as const },
  { code: "g5", name: "Mannerisms & Posturing", description: "Unnatural movements or posture characterised by an awkward, stilted or bizarre appearance.", category: "General" as const },
  { code: "g6", name: "Depression", description: "Feelings of sadness, discouragement, helplessness and pessimism.", category: "General" as const },
  { code: "g7", name: "Motor Retardation", description: "Reduction in motor activity as reflected in slowing of movements and speech.", category: "General" as const },
  { code: "g8", name: "Uncooperativeness", description: "Active refusal to comply with the will of significant others, including the interviewer.", category: "General" as const },
  { code: "g9", name: "Unusual Thought Content", description: "Thinking characterised by strange, fantastic or bizarre ideas.", category: "General" as const },
  { code: "g10", name: "Disorientation", description: "Lack of awareness of one's relationship to the milieu, including persons, place and time.", category: "General" as const },
  { code: "g11", name: "Poor Attention", description: "Failure in focused alertness manifested by poor concentration and distractibility.", category: "General" as const },
  { code: "g12", name: "Lack of Judgement & Insight", description: "Impaired awareness or understanding of one's own psychiatric condition and life situation.", category: "General" as const },
  { code: "g13", name: "Disturbance of Volition", description: "Disturbance in the wilful initiation, sustenance and control of one's thoughts, behaviour, movements and speech.", category: "General" as const },
  { code: "g14", name: "Poor Impulse Control", description: "Disordered regulation and control of action on inner urges.", category: "General" as const },
  { code: "g15", name: "Preoccupation", description: "Absorption with internally generated thoughts and feelings to the detriment of reality orientation.", category: "General" as const },
  { code: "g16", name: "Active Social Avoidance", description: "Diminished social involvement associated with unwarranted fear, hostility or distrust.", category: "General" as const },
]

// ⭐ FIX: Add the combined PANSS_QUESTIONS array that was missing
export const PANSS_QUESTIONS: PANSSQuestion[] = [
  ...POSITIVE_QUESTIONS,
  ...NEGATIVE_QUESTIONS,
  ...GENERAL_QUESTIONS,
]

// ── Fetch PANSS terms ─────────────────────────────────────────────────────────
export async function fetchPANSSPrinciples(): Promise<{ header_description?: string; footer_description?: string }> {
  try {
    const res = await fetch('/api/method/healthcare.api.panss_assessment.get_panss_terms')
    const data = await res.json()
    return data?.message || {}
  } catch (error) {
    console.error('Failed to fetch PANSS terms:', error)
    return {}
  }
}

// ── Calculate scores client-side ──────────────────────────────────────────────
export function calculateScores(ratings: PANSSRatings) {
  const positive_total = ratings.p1 + ratings.p2 + ratings.p3 + ratings.p4 + ratings.p5 + ratings.p6 + ratings.p7
  const negative_total = ratings.n1 + ratings.n2 + ratings.n3 + ratings.n4 + ratings.n5 + ratings.n6 + ratings.n7
  const general_total = ratings.g1 + ratings.g2 + ratings.g3 + ratings.g4 + ratings.g5 + ratings.g6 + 
                        ratings.g7 + ratings.g8 + ratings.g9 + ratings.g10 + ratings.g11 + ratings.g12 +
                        ratings.g13 + ratings.g14 + ratings.g15 + ratings.g16
  const panss_total = positive_total + negative_total + general_total
  const composite_index = positive_total - negative_total
  
  let severity_band = ""
  if (panss_total < 58) severity_band = "Mild"
  else if (panss_total <= 75) severity_band = "Moderate"
  else if (panss_total <= 95) severity_band = "Moderate-Severe"
  else severity_band = "Severe"
  
  return {
    positive_total,
    negative_total,
    general_total,
    panss_total,
    composite_index,
    severity_band
  }
}

// ── Create assessment ─────────────────────────────────────────────────────────
export interface CreatePANSSAssessmentInput extends PANSSRatings {
  patient: string
  assessment_date: string
  rater?: string
  clinical_notes?: string
}

export async function createPANSSAssessment(
  input: CreatePANSSAssessmentInput
): Promise<{ success: boolean; name?: string; message?: string }> {
  const res = await fetch(
    '/api/method/healthcare.api.panss_assessment.create_panss_assessment',
    {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-Frappe-CSRF-Token': (window as any).csrf_token || '',
      },
      body: JSON.stringify({ data: JSON.stringify(input) }),
    }
  )
  const data = await res.json()
  const msg = data?.message
  return msg ?? { success: false, message: 'Unknown error' }
}

// ── Fetch assessments list ────────────────────────────────────────────────────
export async function fetchPANSSAssessments(
  patient?: string,
  search?: string
): Promise<PANSSAssessmentRow[]> {
  const filters: any[] = []
  
  if (patient) filters.push(['patient', '=', patient])
  if (search) filters.push(['patient_name', 'like', `%${search}%`])

  const params = new URLSearchParams({
    fields: JSON.stringify([
      'name', 'patient', 'patient_name', 'assessment_date',
      'rater', 'positive_total', 'negative_total', 'general_total',
      'panss_total', 'composite_index', 'severity_band', 'docstatus', 'clinical_notes'
    ]),
    filters: JSON.stringify(filters),
    limit: '50',
    order_by: 'assessment_date desc',
  })

  const res = await fetch(`/api/resource/PANSS Assessment?${params}`)
  const data = await res.json()

  if (data?.data) {
    return data.data
  }
  
  if (data?.message) {
    return data.message
  }
  
  return []
}